require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# target 'OneSignalNotificationServiceExtension' do
#   pod 'OneSignal', '>= 3.0', '< 4.0'
# end

target 'KardiaChainWallet' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  # Config for QR Scanner
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  target 'KardiaChainWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0','Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
      end
    end
  end
end

target 'KardiaChainWallet-tvOS' do
  # Pods for KardiaChainWallet-tvOS

  target 'KardiaChainWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
